### ISSUE TITLE
3 Track Developers Guide

### ISSUE THREAD

**Issue by darscan** [robotlegs/robotlegs.github.com#1]
Beginner
- Overview
- Installation
- The Context Builder, Bundles & Configs
- Mediators
- Commands
- Dependency Injection
- Common problems
- Communication with the framework (events/signals)
- MVCS Package Structure
- Naming Conventions

Intermediate
- Modularity
- Layers Of Abstraction
- Cyclomatic Complexity
- Async, Flow, State
- Design
- Performance Tuning
- TDD - Testing Mediators/Commands/etc

Advanced
- Writing Extensions
- How the StageWatcher works
- Writing Custom ViewWatchers
- Contributing to the Framework

**Comment by newtriks** [comment]
How about: 

Intermediate
TDD - Testing Mediators/Commands/etc

**Comment by darscan** [comment]
Oh definitely!

**Comment by newtriks** [comment]
I would suggest the below unless you meant to cover these in Flow?

Beginner
Communication within the framework (Events and/or Signals)

**Comment by darscan** [comment]
Good idea. I'll update my original post with these ideas as we go.

**Comment by Ondina** [comment]
Beginner:
- MVCS Package Structure
- Naming Conventions

**Comment by darscan** [comment]
Thanks Ondina!

**Comment by Ondina** [comment]
Intermediate
- Robotlegs Class Diagram (something like the crocus one)
- Robotlegs API (http://api.robotlegs.org/)

**Comment by Ondina** [comment]
# Downloads
- robotlegs
- SwiftSuspenders
- as3-signals
- TDD libraries 

# Quick Start (  or Robotlegs Usage ?)
- Beginner
- Intermediate
- Advanced

# Resources(?)
- Examples, Demos, Articles, Books
- Utilities and Extensions
- Robotlegs Internals:

---- list of Robotlegs staff members

---- link to Robotlegs github repository

---- link to Robotlegs Report Issues

---- Roadmap

---- Robotlegs API

---- Robotlegs Class Diagram - simple (the existing one)

---- Robotlegs Class Diagram - all classes

# Help and Support Forum

+twitter 

Will the website replace the Best Practices? If not, then 
Beginner
*Best Practices Documentation

I would also add a Best Practice for creating demos and utilities: package names (NameOfTheDemo/src/org/robotlegs/demos), what tests are needed, all libraries used for a demo or utility should be provided...

What is Intermediate -  Design?

**Comment by darscan** [comment]
Maybe QuickStart/RobotlegsUsage should be: Developers Guide

**Comment by darscan** [comment]
Yeh, "Intermediate" is about design. We can come up with better names as we go.

**Comment by darscan** [comment]
Ah, and also, this issue is about the QuickStart/DevGuide specifically. I think perhaps the other stuff (Downloads, Resources etc) should go into separate issues?

**Comment by newtriks** [comment]
Dev Guide fits better I think as quick start would only really refer to the "Beginner" aspect of the workflow. Further resources etc sound as though they should be a separate entity however a small link at the bottom of the dev guide to that particular page would be handy?

**Comment by Ondina** [comment]
OK, sorry, I thought it was about the structure of the website in general.

Yes, Developer Guide sounds good

**Comment by darscan** [comment]
No probs, found myself thinking the same thing and then remember that this is the dedicated website repo. Perhaps an issue for General Structure?

**Comment by Ondina** [comment]
yep, General Structure as separate issue

**Comment by Ondina** [comment]
Simon, the idea of having a link to resources in every section as a small link or icon as well is very good, but on the first page it should be as big as possible

**Comment by newtriks** [comment]
Ahhh I maybe confused slightly with how this is all constructed, I thought
that this was a dedicated page similar to the best practices, in which case
== a long scroll down hence a typical URL link. Then at the top of the page
I was in the frame of mind that there would be a menu item link on a nav bar
for the Resources?

**Comment by Ondina** [comment]
Not clear to me either, but I think it’s something for the General Structure issue ( that Shaun will create ?)

**Comment by darscan** [comment]
Woops, sorry it took so long, but have raised a General Structure issue:

https://github.com/robotlegs/robotlegs.github.com/issues/4
