### ISSUE TITLE
General Structure

### ISSUE THREAD

**Issue by darscan** [robotlegs/robotlegs.github.com#4]

**Comment by darscan** [comment]
Originally from: https://github.com/robotlegs/robotlegs.github.com/issues/1#issuecomment-2380243

# Quick View
- Download (zip)
- Changes (log)
- Issues (github)
- Follow (twitter)

# Blog
- Releases
- New extensions
- New demos
- New tutorials

# Libs
- robotlegs-framework
- robotlegs-extensions
- swiftsuspenders
- as3-signals
- TDD libraries

# Docs
- Guide
  - Getting started
  - Intermediate
  - Advanced
  - API
  - Diagrams
- Project
  - Team
  - Get involved
  - Changes
  - Roadmap
- Resources
  - Books
  - Demos
  - Tutorials

# Community & Support
- Knowledgebase
- Twitter & bot
- Issues (github)

**Comment by Ondina** [comment]
It looks good, so far.
