### ISSUE TITLE
Lighthouse & github

### ISSUE THREAD

**Issue by creynders** [robotlegs/robotlegs.github.com#8]
I saw at the current RL site, that Lighthouse is/was used for ticketing. I suppose this will be dropped for the new version?
I have a feeling the github issue API is better than the lighthouse one, and therefore can be more easily integrated into the RLv2 site should the need arise, but I've never worked with neither API's so I'm not sure.

**Comment by darscan** [comment]
Yup, the lighthouse thing didn't really work out and will definitely be dropped going forward.

**Comment by creynders** [comment]
ok, thx, good to know!
